//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CortanaClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HostConfigs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HostConfigs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CortanaClient.HostConfigs", typeof(HostConfigs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;hostCapabilities&quot;: {
        ///		&quot;capabilities&quot;: null
        ///	},
        ///	&quot;choiceSetInputValueSeparator&quot;: &quot;,&quot;,
        ///	&quot;supportsInteractivity&quot;: true,
        ///	&quot;fontFamily&quot;: &quot;Segoe UI&quot;,
        ///	&quot;spacing&quot;: {
        ///		&quot;small&quot;: 3,
        ///		&quot;default&quot;: 8,
        ///		&quot;medium&quot;: 20,
        ///		&quot;large&quot;: 30,
        ///		&quot;extraLarge&quot;: 40,
        ///		&quot;padding&quot;: 10
        ///	},
        ///	&quot;separator&quot;: {
        ///		&quot;lineThickness&quot;: 1,
        ///		&quot;lineColor&quot;: &quot;#FF999999&quot;
        ///	},
        ///	&quot;fontSizes&quot;: {
        ///		&quot;small&quot;: 13,
        ///		&quot;default&quot;: 15,
        ///		&quot;medium&quot;: 18,
        ///		&quot;large&quot;: 20,
        ///		&quot;extraLarge&quot;: 24
        ///	},
        ///	&quot;fontWeights&quot;: {
        ///		&quot;lighter&quot;: 200,
        ///		&quot;default&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CortanaHostConfig {
            get {
                return ResourceManager.GetString("CortanaHostConfig", resourceCulture);
            }
        }
    }
}
